pipeline:
  deploy-fetchd:
    image: google/cloud-sdk:latest
    commands:
      - echo "$$GAE_CREDENTIALS" | base64 -d > /tmp/gcloud.json
      - gcloud auth activate-service-account --key-file /tmp/gcloud.json
      - cd fetch/fetchd
      - sed -i "s/MAIL_KEY/$$MAIL_KEY/g" app.yaml
      - sed -i "s/DB_PWD/$$DB_PWD/g" app.yaml
      - sed -i "s/EMAIL/$$EMAIL/g" app.yaml
      - gcloud beta app deploy --project newshound app.yaml
    version: "${DRONE_COMMIT}"
    secrets:
      - source: google_credentials
        target: GAE_CREDENTIALS
      - source: mail_key
        target: MAIL_KEY
      - source: fetch_pwd
        target: DB_PWD
      - source: email
        target: EMAIL
    when:
      branch: [gae]
      event: push

  publish-np-image:
    image: plugins/gcr
    registry: gcr.io
    repo: newshound/np
    tag: "${DRONE_COMMIT}"
    json_key:
      from_secret: google_credentials
    when:
      branch: [gae]
      event: push

  deploy:
    image: nytimes/drone-gae
    action: deploy
    project: newshound
    dir: np_extractor
    app_file: app.yaml
    addl_args: '{ "--image-url": "gcr.io/newshoun/np:${DRONE_COMMIT}" }'
    version: "${DRONE_COMMIT}"
    secrets:
      - source: google_credentials
        target: GAE_CREDENTIALS
    when:
      branch: [gae]
      event: push
