runtime: go111
service: default

vpc_access_connector:
  name: "projects/newshound/locations/us-central1/connectors/newshound-db"

automatic_scaling:
  max_idle_instances: 1

handlers:
- url: /svc/.*
  script: auto
- url: /
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html
- url: /images/.*
  static_files: frontend/dist/images/\1
  upload: frontend/dist/images/.*
- url: /styles/.*
  static_files: frontend/dist/styles/\1
  upload: frontend/dist/styles/.*
- url: /scripts/.*
  static_files: frontend/dist/scripts/\1
  upload: frontend/dist/scripts/.*
- url: /(.*)
  static_files: frontend/dist/\1
  upload: frontend/dist/.*

env_variables:
  DB_URL: "10.128.0.2"
  DB_USER: fetch
  DB_PASSWORD: "{{ .DB_PWD }}"
