runtime: go111
service: default

vpc_access_connector:
  name: "projects/newshound/locations/us-central1/connectors/newshound-db"

automatic_scaling:
  max_idle_instances: 1

handlers:
- url: /svc/.*
  script: auto
- url: /images
  static_dir: frontend/dist/images
- url: /styles
  static_dir: frontend/dist/styles
- url: /scripts
  static_dir: frontend/dist/scripts
- url: /(.*\.html|ico|png|txt)
  static_dir: frontend/dist
- url: /
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html

env_variables:
  DB_URL: "10.128.0.2"
  DB_USER: fetch
  DB_PASSWORD: "{{ .DB_PWD }}"
