runtime: go111
service: default

vpc_access_connector:
  name: "projects/newshound/locations/us-central1/connectors/newshound-db"

automatic_scaling:
  max_idle_instances: 1

handlers:
- url: /svc/.*
  script: auto
- url: /.*
  static_files: frontend/dist/\1
  upload: frontend/dist/.*\.(html|js|css|ico)$

env_variables:
  DB_URL: "10.128.0.2"
  DB_USER: fetch
  DB_PASSWORD: "{{ .DB_PWD }}"
